/**
 * Shared styles for ResumeForm components.
 */
export const styles = {
    form: {
        width: '100%',
    },
    progressBar: {
        display: 'flex',
        justifyContent: 'space-between',
        marginBottom: '32px',
        position: 'relative',
    },
    progressLine: {
        position: 'absolute',
        top: '16px',
        left: '10%',
        right: '10%',
        height: '2px',
        background: '#E5E7EB',
        zIndex: 0,
    },
    progressLineFill: {
        position: 'absolute',
        top: '16px',
        left: '10%',
        height: '2px',
        background: 'linear-gradient(90deg, #3A4B41, #E6CFA6)',
        zIndex: 1,
        transition: 'width 0.3s ease',
    },
    step: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
        zIndex: 2,
        cursor: 'pointer',
    },
    stepCircle: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '14px',
        fontWeight: '600',
        transition: 'all 0.3s ease',
    },
    stepCircleInactive: {
        background: '#F3F4F6',
        color: '#9CA3AF',
        border: '2px solid #E5E7EB',
    },
    stepCircleActive: {
        background: 'linear-gradient(135deg, #3A4B41, #4A5D52)',
        color: '#E6CFA6',
        border: '2px solid #3A4B41',
        boxShadow: '0 4px 12px rgba(58, 75, 65, 0.3)',
    },
    stepCircleCompleted: {
        background: '#E6CFA6',
        color: '#3A4B41',
        border: '2px solid #E6CFA6',
    },
    stepLabel: {
        fontSize: '14px',
        color: '#6B7280',
        textAlign: 'center',
        maxWidth: '100px',
        marginTop: '4px',
    },
    stepLabelActive: {
        color: '#3A4B41',
        fontWeight: '500',
    },
    stepContent: {
        minHeight: '400px',
    },
    sectionTitle: {
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: '2rem',
        color: '#3A4B41',
        marginBottom: '12px',
        letterSpacing: '1px',
    },
    sectionSubtitle: {
        fontSize: '16px',
        color: '#6B7280',
        marginBottom: '32px',
    },
    formGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
    },
    formGroup: {
        marginBottom: '16px',
    },
    label: {
        display: 'block',
        fontSize: '18px',
        fontWeight: '600',
        color: '#374151',
        marginBottom: '10px',
    },
    input: {
        width: '100%',
        padding: '16px 20px',
        fontSize: '18px',
        border: '2px solid #E5E7EB',
        borderRadius: '14px',
        background: '#FAFAFA',
        transition: 'all 0.2s ease',
        outline: 'none',
    },
    inputFocus: {
        borderColor: '#E6CFA6',
        background: 'white',
        boxShadow: '0 0 0 3px rgba(230, 207, 166, 0.2)',
    },
    textarea: {
        width: '100%',
        padding: '16px 20px',
        fontSize: '18px',
        border: '2px solid #E5E7EB',
        borderRadius: '14px',
        background: '#FAFAFA',
        transition: 'all 0.2s ease',
        outline: 'none',
        minHeight: '150px',
        resize: 'vertical',
        fontFamily: 'inherit',
    },
    select: {
        width: '100%',
        padding: '16px 20px',
        fontSize: '18px',
        border: '2px solid #E5E7EB',
        borderRadius: '14px',
        background: '#FAFAFA',
        transition: 'all 0.2s ease',
        outline: 'none',
        cursor: 'pointer',
    },
    tagInput: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        padding: '8px 12px',
        border: '2px solid #E5E7EB',
        borderRadius: '10px',
        background: '#FAFAFA',
        minHeight: '50px',
        alignItems: 'center',
    },
    tag: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        padding: '6px 12px',
        background: 'linear-gradient(135deg, #3A4B41, #4A5D52)',
        color: '#E6CFA6',
        borderRadius: '20px',
        fontSize: '13px',
        fontWeight: '500',
    },
    tagRemove: {
        background: 'none',
        border: 'none',
        color: '#E6CFA6',
        cursor: 'pointer',
        padding: '0',
        fontSize: '16px',
        lineHeight: '1',
        opacity: '0.8',
    },
    tagInputField: {
        border: 'none',
        background: 'none',
        outline: 'none',
        fontSize: '14px',
        flex: '1',
        minWidth: '100px',
    },
    arrayItem: {
        background: '#F9FAFB',
        borderRadius: '12px',
        padding: '20px',
        marginBottom: '16px',
        border: '1px solid #E5E7EB',
        position: 'relative',
    },
    arrayItemHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
    },
    arrayItemTitle: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#374151',
    },
    removeButton: {
        background: 'none',
        border: 'none',
        color: '#EF4444',
        cursor: 'pointer',
        fontSize: '20px',
        padding: '4px',
        borderRadius: '4px',
    },
    addButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '12px 20px',
        background: '#F3F4F6',
        border: '2px dashed #D1D5DB',
        borderRadius: '10px',
        color: '#6B7280',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        width: '100%',
        justifyContent: 'center',
    },
    navigation: {
        display: 'flex',
        justifyContent: 'space-between',
        marginTop: '32px',
        paddingTop: '24px',
        borderTop: '1px solid #E5E7EB',
    },
    bulletList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    bulletItem: {
        display: 'flex',
        gap: '8px',
        alignItems: 'flex-start',
    },
    bulletInput: {
        flex: '1',
    },
    bulletRemove: {
        background: 'none',
        border: 'none',
        color: '#9CA3AF',
        cursor: 'pointer',
        fontSize: '18px',
        padding: '8px',
    },
}
